(function initializeAuthUi() {
  const copy = {
    hr:{heroTitle:'Mirnije odluke počinju jasnom slikom novca.',heroBody:'Budžeti, pametna štednja i bankovni uvoz u jednom sigurnom radnom prostoru.',benefitOne:'Osobni i poslovni podaci ostaju odvojeni',benefitTwo:'Pametni uvoz uz pregled prije potvrde',benefitThree:'Vaši podaci ostaju na ovom uređaju',eyebrow:'DOBRODOŠLI',loginTitle:'Prijavite se u svoj financijski prostor',loginIntro:'Nastavite ondje gdje ste stali.',login:'Prijava',register:'Registracija',email:'E-mail',password:'Lozinka',fullName:'Ime i prezime',passwordHint:'Najmanje 10 znakova. Lozinka se pretvara u PBKDF2 hash.',loginAction:'Sigurna prijava',registerAction:'Izradi račun',or:'ili',demoAction:'Nastavi u demo načinu',securityNote:'Demo prijava ne traži stvarne bankovne vjerodajnice.',invalidCredentials:'E-mail ili lozinka nisu ispravni.',emailExists:'Račun s tim e-mailom već postoji.',weakPassword:'Lozinka mora imati najmanje 10 znakova.',invalidForm:'Provjerite unesene podatke.'},
    en:{heroTitle:'Calmer decisions start with a clear view of your money.',heroBody:'Budgets, smart savings and bank imports in one focused workspace.',benefitOne:'Personal and Business data remain isolated',benefitTwo:'Smart imports always include a review step',benefitThree:'Your data stays on this device',eyebrow:'WELCOME',loginTitle:'Sign in to your financial workspace',loginIntro:'Continue exactly where you left off.',login:'Sign in',register:'Create account',email:'Email',password:'Password',fullName:'Full name',passwordHint:'At least 10 characters. Your password is converted into a PBKDF2 hash.',loginAction:'Secure sign in',registerAction:'Create account',or:'or',demoAction:'Continue in demo mode',securityNote:'Demo sign-in never asks for real bank credentials.',invalidCredentials:'The email or password is incorrect.',emailExists:'An account with that email already exists.',weakPassword:'Use at least 10 characters.',invalidForm:'Check the information and try again.'}
  };
  const provider = MerAuth.createLocalProvider();
  window.MerAuthProvider = provider;
  const authShell=document.getElementById('authShell'),appShell=document.getElementById('appShell');

  function lang(){return typeof currentLang!=='undefined'&&currentLang==='en'?'en':'hr';}
  function renderCopy(){document.querySelectorAll('[data-auth-copy]').forEach(element=>{const value=copy[lang()][element.dataset.authCopy];if(value)element.textContent=value;});}
  function selectMode(mode){const register=mode==='register';document.getElementById('loginForm').hidden=register;document.getElementById('registerForm').hidden=!register;document.getElementById('authLoginTab').classList.toggle('active',!register);document.getElementById('authRegisterTab').classList.toggle('active',register);document.getElementById('authLoginTab').setAttribute('aria-selected',String(!register));document.getElementById('authRegisterTab').setAttribute('aria-selected',String(register));document.getElementById('authTitle').dataset.authCopy=register?'register':'loginTitle';document.getElementById('authTitle').textContent=register?copy[lang()].register:copy[lang()].loginTitle;}
  function applyUser(session){if(!session||session.demo)return;const profile=appState.accounts.personal;profile.accountName=session.name;profile.initials=session.name.split(/\s+/).map(part=>part[0]).join('').slice(0,2).toUpperCase();state=appState.accounts[appState.activeAccount];save('auth-profile');}
  function enterApp(session){applyUser(session);authShell.hidden=true;appShell.hidden=false;document.body.classList.remove('auth-pending','auth-visible');if(appState.mfa.enabled&&sessionStorage.getItem('mer-mfa-unlocked')!=='true'){document.getElementById('mfaLockScreen').hidden=false;document.body.classList.add('mfa-locked');}renderCopy();renderAll();}
  function showAuth(){document.getElementById('mfaLockScreen').hidden=true;document.body.classList.remove('mfa-locked');appShell.hidden=true;authShell.hidden=false;document.body.classList.remove('auth-pending');document.body.classList.add('auth-visible');renderCopy();selectMode('login');setTimeout(()=>document.getElementById('loginEmail').focus(),30);}
  const messageFor=code=>code==='EMAIL_EXISTS'?copy[lang()].emailExists:code==='WEAK_PASSWORD'?copy[lang()].weakPassword:code==='INVALID_CREDENTIALS'?copy[lang()].invalidCredentials:copy[lang()].invalidForm;

  document.getElementById('authLoginTab').addEventListener('click',()=>selectMode('login'));
  document.getElementById('authRegisterTab').addEventListener('click',()=>selectMode('register'));
  document.getElementById('demoLogin').addEventListener('click',()=>enterApp(provider.startDemo(appState.accounts.personal.accountName)));
  document.getElementById('loginForm').addEventListener('submit',async event=>{event.preventDefault();const result=await provider.signIn({email:document.getElementById('loginEmail').value,password:document.getElementById('loginPassword').value});document.getElementById('loginError').textContent=result.ok?'':messageFor(result.code);if(result.ok)enterApp(result.session);});
  document.getElementById('registerForm').addEventListener('submit',async event=>{event.preventDefault();const result=await provider.register({name:document.getElementById('registerName').value,email:document.getElementById('registerEmail').value,password:document.getElementById('registerPassword').value});document.getElementById('registerError').textContent=result.ok?'':messageFor(result.code);if(result.ok)enterApp(result.session);});
  document.getElementById('logoutButton').addEventListener('click',()=>{provider.signOut();sessionStorage.removeItem('mer-mfa-unlocked');toggleAccountMenu(false);showAuth();});
  document.querySelectorAll('[data-lang]').forEach(button=>button.addEventListener('click',renderCopy));

  const session=provider.currentSession();if(session)enterApp(session);else showAuth();
})();
