'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const E=require('../engagement-core.js'),Demo=require('../demo-data.js'),Store=require('../state-store.js');
function profile(){return {profileId:'personal',currency:'EUR',bills:100,goalBuckets:[{id:'reserve',current:600,primary:true}],categories:[{id:'food',limit:100},{id:'transport',limit:200}],transactions:[{id:'income',type:'income',amount:1000,date:'2026-09-01'},{id:'expense',type:'expense',category:'food',amount:150,date:'2026-09-02'}],savingsEntries:[{id:'saving',goalId:'reserve',amount:200,date:'2026-09-03'},{id:'roundup:x',sourceType:'round-up',goalId:'reserve',amount:.8,date:'2026-09-03'}]};}
const opt={profileId:'personal',referenceDate:'2026-09-08',currency:'EUR'};
test('cycle 1: cancelled amounts and foreign duplicate category IDs do not leak',()=>{const p=profile();p.categories.unshift({id:'food',profileId:'business',limit:999});p.transactions.push({id:'cancelled',type:'income',amount:9000,date:'2026-09-03',status:'cancelled'});const proposal=E.rebalance(p,opt);E.applyRebalance(p,proposal,opt);assert.equal(p.categories[0].limit,999);assert.equal(p.categories[1].limit,150);assert.equal(E.health(p,opt).incomeCents,100000);p.transactions.push({id:'unknown',type:'expense',category:'unknown',amount:200,date:'2026-09-03'});assert.equal(E.health(p,opt).overCents,20000);});
test('cycle 1: health uses posted income, actual net vault deposits and weighted budget adherence',()=>{const result=E.health(profile(),opt);assert.equal(result.incomeCents,100000);assert.equal(result.savedCents,20080);assert.equal(result.overCents,5000);assert.equal(result.bufferMonths,6);assert.equal(result.score,94);assert.equal(result.recommendations.length,3);});
test('cycle 1: rebalance preserves exact cents, never changes real money, requires non-stale proposal',()=>{const p=profile(),before=structuredClone(p),proposal=E.rebalance(p,opt);assert.deepEqual(p,before);assert.equal(proposal.rows[0].newLimitCents,15000);assert.equal(proposal.rows[1].newLimitCents,15000);assert.equal(proposal.rows.reduce((sum,row)=>sum+row.newLimitCents,0),30000);E.applyRebalance(p,proposal,opt);assert.deepEqual(p.transactions,before.transactions);assert.throws(()=>E.applyRebalance(p,proposal,opt),/STALE/);});
test('cycle 1: shortfall cannot manufacture allocation, empty profile has no fake high score',()=>{const p=profile();p.categories[1].limit=0;const result=E.rebalance(p,opt);assert.equal(result.shortfallCents,5000);assert.equal(result.changed,false);p.transactions=[];assert.equal(E.health(p,opt).score,null);});
test('cycle 1: wrapped isolates profiles/currencies, exclusions, refunds, savings withdrawals, roundups subset',()=>{const p=profile();p.transactions.push({type:'income',profileId:'business',amount:100000,date:'2026-09-03'},{type:'income',currency:'USD',amount:99999,date:'2026-09-02'},{type:'expense',amount:1000,category:'food',date:'2026-09-09'},{type:'expense',amount:1000,category:'food',status:'pending',date:'2026-09-03'},{type:'expense',amount:1000,category:'food',offlineDraft:true,date:'2026-09-03'},{type:'expense',amount:-10,category:'food',date:'2026-09-03'});p.savingsEntries.push({amount:-50,date:'2026-09-03',goalId:'reserve'});const result=E.monthlySummary(p,{...opt,month:'2026-09'});assert.equal(result.incomeCents,100000);assert.equal(result.expenseCents,14000);assert.equal(result.savedCents,15080);assert.equal(result.roundupCents,80);assert.equal(result.vaultCents,15080);assert.equal(result.biggest.amountCents,15000);assert.throws(()=>E.health(p,{...opt,profileId:'business'}));});
test('cycle 1: monthly trigger once per user/profile, leap year and year rollover',()=>{assert.equal(E.previousMonth('2028-03-01'),'2028-02');assert.equal(E.previousMonth('2027-01-01'),'2026-12');assert.throws(()=>E.previousMonth('2026-02-30'));const p=profile(),settings={...opt,referenceDate:'2026-09-01'};assert.equal(E.shouldAutoOpen(p,'user1',settings),true);const key=E.wrappedKey('user1','personal',settings.referenceDate);p.engagement={wrappedSeen:{[key]:true}};assert.equal(E.shouldAutoOpen(p,'user1',settings),false);assert.equal(E.shouldAutoOpen(p,'user2',settings),true);assert.equal(E.shouldAutoOpen(p,'user1',opt),false);});
test('cycle 1: rapid store mutations remain mathematically coherent and business isolated',()=>{const store=Store.createStore(Demo.createDemoAppState(new Date('2026-09-08T12:00:00')),{referenceDate:opt.referenceDate});const business=structuredClone(store.getState().accounts.business);delete business.derived;for(let i=0;i<80;i++)store.update('stress',draft=>{draft.accounts.personal.transactions.push({id:`stress-${i}`,type:i%2?'expense':'income',amount:i+.01,category:'food',date:'2026-09-08',profileId:'personal',currency:'EUR'});});const result=E.health(store.getActiveProfile(),opt);assert.ok(Number.isFinite(result.score));assert.ok(result.score>=0&&result.score<=100);const after=structuredClone(store.getState().accounts.business);delete after.derived;assert.deepEqual(after,business);});
