'use strict';
const assert=require('node:assert/strict');
const Vault=require('../vault-core.js');
const Auth=require('../auth-core.js');
const memory=()=>{const values=new Map();return{getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,String(value)),removeItem:key=>values.delete(key),keys:()=>[...values.keys()],get length(){return values.size;},key:index=>[...values.keys()][index]||null};};
async function run(){
  const storage=memory(),payload={accounts:{personal:{transactions:[{id:'p',amount:12.45}]},business:{transactions:[{id:'b',amount:999.33}]}}},password='A long private passphrase 123';
  const vault=Vault.createVault({storage,userId:'owner-a'});
  await vault.enable(password,payload);
  assert.equal(vault.isUnlocked(),true);
  const raw=storage.getItem(vault.storageKey);
  assert.equal(raw.includes('transactions'),false);assert.equal(raw.includes(password),false);
  assert.equal(JSON.parse(raw).algorithm,'AES-256-GCM');assert.equal(storage.keys().length,1,'No encryption key beside ciphertext');
  const first=structuredClone(payload),last=structuredClone(payload);first.accounts.personal.transactions[0].amount=111;last.accounts.personal.transactions[0].amount=222;
  const writes=[vault.persist(first),vault.persist(last)];last.accounts.personal.transactions[0].amount=333;
  await Promise.all(writes);await vault.lock();
  assert.equal(vault.isUnlocked(),false);
  await assert.rejects(vault.persist(payload),{code:'VAULT_LOCKED'});
  await assert.rejects(vault.unlock('wrong password value'),{code:'VAULT_UNLOCK_FAILED'});
  const restored=await vault.unlock(password);assert.equal(restored.accounts.personal.transactions[0].amount,222,'Serialized write order and immutable snapshots');assert.equal(restored.accounts.business.transactions[0].amount,999.33,'Business profile does not bleed');
  const second=Vault.createVault({storage,userId:'owner-b'});storage.setItem(second.storageKey,storage.getItem(vault.storageKey));
  await assert.rejects(second.unlock(password),{code:'INVALID_VAULT'});
  const swapped=JSON.parse(storage.getItem(vault.storageKey));swapped.userId='owner-b';storage.setItem(second.storageKey,JSON.stringify(swapped));
  await assert.rejects(second.unlock(password),{code:'VAULT_UNLOCK_FAILED'},'AAD binds ciphertext to exact user');
  const valid=storage.getItem(vault.storageKey),corrupt=JSON.parse(valid);const buffer=Buffer.from(corrupt.ciphertext,'base64');buffer[0]^=1;corrupt.ciphertext=buffer.toString('base64');storage.setItem(vault.storageKey,JSON.stringify(corrupt));
  await assert.rejects(vault.unlock(password),{code:'VAULT_UNLOCK_FAILED'},'Tamper must fail closed');storage.setItem(vault.storageKey,valid);
  await vault.unlock(password);await vault.changePassphrase('Different replacement password 987');await vault.lock();
  await assert.rejects(vault.unlock(password),{code:'VAULT_UNLOCK_FAILED'});assert.equal((await vault.unlock('Different replacement password 987')).accounts.personal.transactions[0].amount,222);
  const quotaStorage={...memory(),setItem(){throw new Error('QuotaExceededError');}};const quota=Vault.createVault({storage:quotaStorage,userId:'quota'});
  await assert.rejects(quota.enable(password,payload),/QuotaExceededError/);assert.equal(quota.isUnlocked(),false);
  let now=0,locks=0;const idle=Vault.createIdleClock({now:()=>now,onLock:()=>locks++});
  now=599999;assert.equal(idle.check(),false);now=600000;assert.equal(idle.activity(),false,'Activity at the deadline cannot defeat the lock');assert.equal(locks,1);now=700000;idle.check();assert.equal(locks,1);
  idle.reset();now=900000;assert.equal(idle.activity(),true);now=1499999;assert.equal(idle.check(),false);now=1500000;assert.equal(idle.check(),true);
  idle.reset();now-=100;assert.equal(idle.check(),true,'Clock rollback must not extend timeout');
  const portable=Vault.portableSnapshot({...payload,mfa:{secret:'secret'},mfaByUser:{other:{secret:'hidden'}},bankConnections:[{iban:'HR123',accessToken:'token'}]});
  assert.equal(JSON.stringify(portable).includes('secret'),false);assert.equal(JSON.stringify(portable).includes('token'),false);assert.equal(portable.data.bankConnections[0].iban,'HR123');
  const portabilitySecrets=Vault.portableSnapshot({...payload,auth:{token:'do-not-export'},session:{id:'session-proof'},bankConnections:[{iban:'HR456',access_token:'a',refresh_token:'b',id_token:'c',client_secret:'d',api_key:'e',credentials:{password:'f'}}]});
  assert.deepEqual(portabilitySecrets.data.bankConnections,[{iban:'HR456'}]);assert.equal(portabilitySecrets.data.auth,undefined);assert.equal(portabilitySecrets.data.session,undefined);
  const mfaInput={...payload,mfa:{enabled:true,secret:'other-secret'},mfaByUser:{'owner-a':{enabled:true,secret:'own-secret'},'owner-b':{enabled:true,secret:'other-secret'}},mfaLegacyOwner:'owner-b'};
  const mfaScoped=Vault.scopeSnapshot(mfaInput,'owner-a');assert.deepEqual(Object.keys(mfaScoped.mfaByUser),['owner-a']);assert.equal(mfaScoped.mfa.secret,'own-secret');assert.equal(JSON.stringify(mfaScoped).includes('other-secret'),false);assert.equal(Object.keys(mfaInput.mfaByUser).length,2,'Scoping does not mutate source');
  const deletionStorage=memory();['mer-layout-v1:owner-a--personal:overview','mer-layout-v1:owner-a--business:insights','mer-layout-v1:owner-ab--personal:overview','mer-onboarding-v1:owner-a','mer-onboarding-v1:owner-b','mer-cache-v1:owner-b'].forEach(key=>deletionStorage.setItem(key,'saved'));
  Vault.localUserKeys(deletionStorage,'owner-a').forEach(key=>deletionStorage.removeItem(key));assert.equal(deletionStorage.getItem('mer-layout-v1:owner-a--personal:overview'),null);assert.equal(deletionStorage.getItem('mer-layout-v1:owner-a--business:insights'),null);assert.equal(deletionStorage.getItem('mer-layout-v1:owner-ab--personal:overview'),'saved');assert.equal(deletionStorage.getItem('mer-onboarding-v1:owner-b'),'saved');assert.equal(deletionStorage.getItem('mer-cache-v1:owner-b'),'saved');
  const usersStorage=memory(),tabA=memory(),tabB=memory();const a=Auth.createLocalProvider({usersStorage,sessionStorage:tabA}),b=Auth.createLocalProvider({usersStorage,sessionStorage:tabB});
  const ra=await a.register({name:'One User',email:'one@example.test',password:'registered-password-1'}),rb=await b.register({name:'Two User',email:'two@example.test',password:'registered-password-2'});
  assert.equal((await a.verifyCurrentPassword('incorrect')).ok,false);assert.equal((await a.deleteCurrentUser('incorrect')).ok,false);
  assert.equal((await a.deleteCurrentUser('registered-password-1')).ok,true);assert.equal(a.currentSession(),null);assert.equal(b.currentSession().userId,rb.session.userId);assert.equal(JSON.parse(usersStorage.getItem(Auth.USERS_KEY)).some(user=>user.id===ra.session.userId),false);
  process.stdout.write('PASS enterprise security cycle 1: AES-256-GCM tamper/user isolation, ordered writes, password rotation, idle boundary, scoped deletion.\n');
}
run().catch(error=>{process.stderr.write(`${error.stack}\n`);process.exitCode=1;});
