'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const core=require('../household-core.js');
const context={userId:'owner',displayName:'Owner',profileId:'business'};
let space=core.createSpace({id:'business-shared',name:'Zajednički ured',currency:'EUR'},context);
space=core.reduceSpace(space,'owner',{type:'addMember',payload:{id:'partner',name:'Partner',role:'editor'}});
space=core.reduceSpace(space,'owner',{type:'addContribution',payload:{id:'future',memberId:'owner',amountCents:50000,date:'2028-02-29'}});
assert.equal(core.summary(space,'2028-02-28').availableCents,0,'Future contribution cannot increase present balance');assert.equal(core.summary(space,'2028-02-29').availableCents,50000);
for(let index=0;index<40;index+=1)space=core.reduceSpace(space,'owner',{type:'addBill',payload:{id:`bill-${index}`,name:`Uredski račun ${index+1}`,amountCents:103+index,dueDate:'2028-02-29'}});
const total=space.bills.reduce((sum,bill)=>sum+bill.amountCents,0);assert.equal(core.summary(space,'2028-03-01').upcomingCents,total);assert.equal(core.summary(space,'2028-03-01').overdueCount,40);
const malicious=structuredClone(space);malicious.bills[0].shares.owner=999999999;assert.equal(core.summary(malicious,'2028-03-01').members.reduce((sum,member)=>sum+member.openShareCents,0),total,'Derived split ignores stale/tampered cached shares');
const invalid=structuredClone(space);invalid.members.push({id:'intruder',name:'Intruder',role:'owner'});assert.deepEqual(core.listSpaces({enterprise:{households:[invalid]}},context),[],'Malformed multiple-owner state is rejected');
assert.throws(()=>core.reduceSpace(space,'owner',{type:'removeMember',payload:{id:'partner'}}),{code:'MEMBER_IN_USE'});
const profile={transactions:[{id:'private',amount:900}],enterprise:{households:[space]}};const borrowed=core.listSpaces(profile,context);borrowed[0].bills[0].name='Changed';assert.notEqual(profile.enterprise.households[0].bills[0].name,'Changed','Read snapshots cannot mutate global state');
const source=fs.readFileSync(require.resolve('../household-ui.js'),'utf8');new vm.Script(source);
assert.match(source,/root\.MerEnterpriseSecurity\?\.isLocked\(\)/);assert.match(source,/sameContext\(\)/);assert.match(source,/previewSpace=core\.reduceSpace/);assert.match(source,/Member preview — trial changes are not saved/);assert.match(source,/No invitations or network synchronization/);
assert.match(source,/aria-labelledby/);assert.match(source,/bindDialogBackdropDismiss/);assert.match(source,/data-monetary/);assert.match(source,/slice\(\(page-1\)\*8,page\*8\)/);
const css=fs.readFileSync(require.resolve('../household.css'),'utf8');assert.match(css,/max-height:90dvh/);assert.match(css,/min-height:0;overflow-y:auto;overflow-x:hidden/);assert.match(css,/@media\(max-width:414px\)/);assert.match(css,/min-height:44px/);
process.stdout.write('PASS household cycle 2: 40-bill stress, future dates/leap day, malformed-state handling, preview honesty, modal/touch/responsive guards.\n');
