'use strict';
const assert=require('node:assert/strict');
const core=require('../household-core.js');
const owner={userId:'user-owner',displayName:'Mer Owner',profileId:'personal'};
const personal={transactions:[{id:'private-1',amount:350}],availableBalance:2840,goalBuckets:[{id:'private-goal',current:450}],enterprise:{invoices:[]}},business={transactions:[{id:'biz-1',amount:6000}],availableBalance:9000};
const privateBefore=JSON.stringify(personal.transactions),goalsBefore=JSON.stringify(personal.goalBuckets),businessBefore=JSON.stringify(business);
const space=core.createInProfile(personal,{id:'home-one',name:'Naš dom',currency:'EUR'},owner);
assert.equal(space.ownerUserId,owner.userId);assert.equal(space.mode,'local-only');
core.applyCommand(personal,owner,space.id,{type:'addMember',payload:{id:'partner-editor',name:'Partner',role:'editor'}});
core.applyCommand(personal,owner,space.id,{type:'addMember',payload:{id:'guest-viewer',name:'Član obitelji',role:'viewer'}});
let current=core.listSpaces(personal,owner)[0];
assert.equal(core.permissions('viewer').manageBills,false);assert.equal(core.permissions('editor').manageBills,true);assert.equal(core.permissions('editor').manageMembers,false);
assert.deepEqual(core.listSpaces(personal,{...owner,userId:'other-user'}),[]);assert.deepEqual(core.listSpaces(personal,{...owner,profileId:'business'}),[]);assert.deepEqual(core.listSpaces(personal,{...owner,userId:'partner-editor'}),[],'Local member alias is not an authenticated shared account');
assert.throws(()=>core.applyCommand(personal,{...owner,userId:'partner-editor'},space.id,{type:'rename',payload:{name:'Hacked'}}),{code:'ACCESS_DENIED'});
assert.throws(()=>core.reduceSpace(current,'stranger',{type:'addBill',payload:{}}),{code:'ACCESS_DENIED'});
assert.throws(()=>core.reduceSpace(current,'guest-viewer',{type:'addBill',payload:{}}),{code:'PERMISSION_DENIED'});
assert.throws(()=>core.reduceSpace(current,'partner-editor',{type:'editMember',payload:{id:'partner-editor',role:'owner'}}),{code:'PERMISSION_DENIED'});
assert.throws(()=>core.reduceSpace(current,owner.userId,{type:'removeMember',payload:{id:owner.userId}}),{code:'OWNER_PROTECTED'});
const preview=core.reduceSpace(current,'partner-editor',{type:'addBill',payload:{id:'trial-bill',name:'Probna struja',amountCents:10000,dueDate:'2026-09-15'}});
assert.equal(preview.bills.length,1);assert.equal(current.bills.length,0,'Permission preview never mutates saved owner state');assert.equal(core.listSpaces(personal,owner)[0].bills.length,0);
assert.deepEqual(preview.bills[0].shares,{'user-owner':3334,'partner-editor':3333,'guest-viewer':3333});assert.equal(Object.values(preview.bills[0].shares).reduce((a,b)=>a+b,0),10000);
core.applyCommand(personal,owner,space.id,{type:'addBill',payload:{id:'power',name:'Struja',amountCents:10000,dueDate:'2026-09-15',memberIds:[owner.userId,'partner-editor']}});
core.applyCommand(personal,owner,space.id,{type:'addContribution',payload:{id:'deposit-owner',memberId:owner.userId,amountCents:15000,date:'2026-09-01'}});
core.applyCommand(personal,owner,space.id,{type:'addContribution',payload:{id:'deposit-partner',memberId:'partner-editor',amountCents:10000,date:'2026-09-02'}});
current=core.listSpaces(personal,owner)[0];let summary=core.summary(current,'2026-09-07');
assert.equal(summary.availableCents,25000);assert.equal(summary.upcomingCents,10000);assert.equal(summary.afterBillsCents,15000);assert.equal(summary.coveragePercent,100);
core.applyCommand(personal,owner,space.id,{type:'markPaid',payload:{id:'power',date:'2026-09-07'}});summary=core.summary(core.listSpaces(personal,owner)[0],'2026-09-07');
assert.equal(summary.paidCents,10000);assert.equal(summary.availableCents,15000);assert.equal(summary.upcomingCents,0);assert.equal(summary.members[1].paidShareCents,5000);
assert.throws(()=>core.applyCommand(personal,owner,space.id,{type:'editBill',payload:{id:'power',name:'Struja',amountCents:5000,dueDate:'2026-09-15'}}),{code:'PAID_BILL_LOCKED'});
core.applyCommand(personal,owner,space.id,{type:'reopenBill',payload:{id:'power'}});assert.equal(core.summary(core.listSpaces(personal,owner)[0],'2026-09-07').availableCents,25000);
assert.equal(JSON.stringify(personal.transactions),privateBefore);assert.equal(JSON.stringify(personal.goalBuckets),goalsBefore);assert.equal(personal.availableBalance,2840);assert.equal(JSON.stringify(business),businessBefore,'Household ledger does not touch personal/business balances or goals');
assert.equal(core.parseAmountCents('100,05'),10005);assert.equal(core.parseAmountCents('0.01'),1);for(const value of ['-1','NaN','Infinity','1.999','1e3',''])assert.throws(()=>core.parseAmountCents(value),{code:'INVALID_AMOUNT'});
assert.equal(core.validDate('2028-02-29'),true);assert.equal(core.validDate('2027-02-29'),false);
assert.throws(()=>core.reduceSpace(current,owner.userId,{type:'addBill',payload:{id:'bad-date',name:'Trošak',amountCents:20,dueDate:'2027-02-29'}}),{code:'INVALID_DATE'});
assert.throws(()=>core.reduceSpace(current,owner.userId,{type:'addBill',payload:{id:'bad-currency',name:'Trošak',amountCents:20,dueDate:'2026-10-01',currency:'USD'}}),{code:'CURRENCY_MISMATCH'});
assert.throws(()=>core.splitEvenly(10,['__proto__']),{code:'INVALID_MEMBERS'});
process.stdout.write('PASS household cycle 1: exact-cent splits, role permissions, immutable role preview, strict user/profile/financial ledger isolation.\n');
